URL = 'https://www.dafabet.com/en/sports/'
LOGIN = ''
PASSWORD = ''

EXPLICITLY_WAIT_BETFRAME_LOADING = 15
EXPLICITLY_WAIT_LEAGUES_LOADING = 15

IMPLICITLY_WAIT_ELEMENTS = 15
IMPLICITLY_WAIT_FRAMES = 100

WINDOWS_SIZE = (1920, 1080)
